export const types = {
  FETCH_USERS_PENDING: "FETCH_USERS_PENDING",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",

  FETCH_SEARCHED_USERS_LIST_SUCCESS: "FETCH_SEARCHED_USERS_LIST_SUCCESS",
  HIDE_SEARCHED_USERS_LIST: "HIDE_SEARCHED_USERS_LIST",

  FETCH_SINGLE_USER_SUCCESS: "FETCH_SINGLE_USER_SUCCESS",
};
